# Generated by Django 3.2.9 on 2021-12-05 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Username',
        ),
    ]
